querydata=(
    args=(
        dtools='inv alarm alarmstat'
        vtools='alarmstatchart'
    )
    dt_inv=(
        poutlevel=o
        soutlevel=
        runinparallel=y
    )
    dt_alarm=(
        inlevels=o
    )
    dt_alarmstat=(
        inlevels=o
    )
    vt_alarmstatchart=(
    )
)
