#!/bin/ksh

for i in exec netdisc ping port scopeinv snmp ssh telnet url wmi; do
    if [[ -d ../$i ]] then
        print -u2 saving old scope software for $i protocol
        mkdir -p ../saved.pre8.10
        mv ../$i ../saved.pre8.10
    fi
done
