:PACKAGE: graphviz ast

CCFLAGS += $$(CC.DLL)

graph 1.0 :LIBRARY: agxbuf.c attribs.c edge.c graph.c graphio.c lexer.c node.c \
	parser.c refstr.c trie.c graph.ign

$(INCLUDEDIR) :INSTALLDIR: \
graph.h
