#!/bin/ksh

export TZ=SWIFT_CFG_SYSTZ

function add2path {
    export PATH=$1/bin:$PATH
    export FPATH=$1/fun:$FPATH
    export SWIFT_CFG_LDLIBRARYPATH=$1/lib:$SWIFT_CFG_LDLIBRARYPATH
}

if [[ ! -f SWIFT_CFG_DSCOPESDIR/active ]] then
    exit 0
fi

add2path SWIFT_CFG_SSYSTEMDIR/current
add2path SWIFT_CFG_SSNMPDIR/current
[[ -x SWIFT_CFG_SSYSTEMDIR/current/bin/ksh ]] && \
export SHELL=SWIFT_CFG_SSYSTEMDIR/current/bin/ksh
export SHELLVERSION=SWIFT_CFG_SHELLVERSION
[[ $KSHREC != 1 && ${KSH_VERSION##*' '} < $SHELLVERSION ]] && \
KSHREC=1 exec $SHELL $0 "$@"

export MIBDIRS=SWIFT_CFG_SSNMPDIR/current/mibs

export VG_SYSNAME=SWIFT_CFG_SYSNAME
export VG_SYSMODE=SWIFT_CFG_SYSMODE

export VG_SSYSTEMDIR=SWIFT_CFG_SSYSTEMDIR
export VG_SSCOPESDIR=SWIFT_CFG_SSCOPESDIR
export VG_SWWWDIR=SWIFT_CFG_SWWWDIR
export VG_SSNMPDIR=SWIFT_CFG_SSNMPDIR
export VG_DSYSTEMDIR=SWIFT_CFG_DSYSTEMDIR
export VG_DSCOPESDIR=SWIFT_CFG_DSCOPESDIR
export VG_DWWWDIR=SWIFT_CFG_DWWWDIR
export VG_DSNMPDIR=SWIFT_CFG_DSNMPDIR

export LC_ALL=C LANG=C

PATH=$PATH:/usr/sbin:/sbin

if [[ $1 == update ]] then
    cat > SWIFT_CFG_DSCOPESDIR/schedule.new || exit 1
    size=$(ls -Z '%(size)d' SWIFT_CFG_DSCOPESDIR/schedule.new)
    if [[ $3 == +([0-9]) && $3 != $size ]] then
        exit 1
    elif [[
        $3 != 0 && $(tail -1 SWIFT_CFG_DSCOPESDIR/schedule.new) != *'</cfg>'*
    ]] then
        exit 1
    fi
    rm -f SWIFT_CFG_DSCOPESDIR/schedule.bak
    cp SWIFT_CFG_DSCOPESDIR/schedule SWIFT_CFG_DSCOPESDIR/schedule.bak
    mv SWIFT_CFG_DSCOPESDIR/schedule.new SWIFT_CFG_DSCOPESDIR/schedule
    print size=$(ls -Z '%(size)d' SWIFT_CFG_DSCOPESDIR/schedule)
    exit 0
fi

if [[ $1 == reinv ]] then
    for i in SWIFT_CFG_DSCOPESDIR/data/*.$2; do
        if [[ -d $i ]] then
            rm -f $i/inv.out
            print ok
            exit 0
        fi
    done
    exit 0
fi

if [[ $1 == getfiles ]] then
    dirs=
    for i in SWIFT_CFG_DSCOPESDIR/data/*.$2; do
        if [[ -d $i ]] then
            dirs+=" ${i#SWIFT_CFG_DSCOPESDIR/data/}"
        fi
    done
    print TARSTARTSNOW
    ( cd SWIFT_CFG_DSCOPESDIR/data && tar cf - $dirs )
    exit 0
fi

$SHELL SWIFT_CFG_DSCOPESDIR/etc/timediff
VMALLOC_OPTIONS=break $SHELL vg_scheduler SWIFT_CFG_DSCOPESDIR/schedule
