#!/bin/ksh

export TZ=SWIFT_CFG_SYSTZ

function add2path {
    export PATH=$1/bin:$PATH
    export FPATH=$1/fun:$FPATH
    export SWIFT_CFG_LDLIBRARYPATH=$1/lib:$SWIFT_CFG_LDLIBRARYPATH
}

if [[ ! -f SWIFT_CFG_DSCOPESDIR/active ]] then
    exit 0
fi

add2path SWIFT_CFG_SSYSTEMDIR/current
add2path SWIFT_CFG_SSNMPDIR/current
[[ -x SWIFT_CFG_SSYSTEMDIR/current/bin/ksh ]] && \
export SHELL=SWIFT_CFG_SSYSTEMDIR/current/bin/ksh
export SHELLVERSION=SWIFT_CFG_SHELLVERSION
[[ $KSHREC != 1 && ${KSH_VERSION##*' '} < $SHELLVERSION ]] && \
KSHREC=1 exec $SHELL $0 "$@"

function ts {
    printf '%(%Y/%m/%d %H:%M:%S)T'
}

export VG_SYSNAME=SWIFT_CFG_SYSNAME
export VG_SYSMODE=SWIFT_CFG_SYSMODE

export VG_SSYSTEMDIR=SWIFT_CFG_SSYSTEMDIR
export VG_SSCOPESDIR=SWIFT_CFG_SSCOPESDIR
export VG_SWWWDIR=SWIFT_CFG_SWWWDIR
export VG_SSNMPDIR=SWIFT_CFG_SSNMPDIR
export VG_DSYSTEMDIR=SWIFT_CFG_DSYSTEMDIR
export VG_DSCOPESDIR=SWIFT_CFG_DSCOPESDIR
export VG_DWWWDIR=SWIFT_CFG_DWWWDIR
export VG_DSNMPDIR=SWIFT_CFG_DSNMPDIR

export LC_ALL=C LANG=C

PATH=$PATH:/usr/sbin:/sbin

cd $VG_DSCOPESDIR/data || exit 1

[[ -f ../etc/scheduler.info ]] && . ../etc/scheduler.info
VG_INVSECS=${VG_INVSECS:-86400}

typeset -A dirs
tw -i -e 'name=="spec.sh" && mtime > "1 hour ago"' -e 'sort:mtime' \
| while read file; do
    [[ -f ${file%/*}/inv.out ]] && dirs[${file%/*}]=1
done

invn=${#dirs[@]}
float invi=0
[[ $invn == 0 ]] && exit 0

ct=$(printf '%(%#)T')
tw -i -e 'name=="inv.out"' -e 'action:printf ("%d %s\n", mtime, path)' \
| while read mtime file; do
    [[ $dirs[${file%/*}] == '' ]] && continue
    (( t = (ct - VG_INVSECS) + VG_INVSECS * (invi / invn) ))
    touch -t "#${t%.*}" $file
    (( invi += 1.0 ))
done

exit 0
