#!/bin/ksh

function add2path {
    export PATH=$1/bin:$PATH
    export FPATH=$1/fun:$FPATH
    export SWIFT_CFG_LDLIBRARYPATH=$1/lib:$SWIFT_CFG_LDLIBRARYPATH
}

if [[ ! -f SWIFT_CFG_DWWWDIR/active ]] then
    exit 0
fi

add2path SWIFT_CFG_DWWWDIR
add2path SWIFT_CFG_SSYSTEMDIR/current
[[ -x SWIFT_CFG_SSYSTEMDIR/current/bin/ksh ]] && \
export SHELL=SWIFT_CFG_SSYSTEMDIR/current/bin/ksh
export SHELLVERSION=SWIFT_CFG_SHELLVERSION
[[ $KSHREC != 1 && ${KSH_VERSION##*' '} < $SHELLVERSION ]] && \
KSHREC=1 exec $SHELL $0 "$@"

export LC_ALL=C LANG=C

add2path SWIFT_CFG_SWWWDIR/current

typeset -A ids groups

exec > SWIFT_CFG_DWWWDIR/logs/loaddbm_log 2>&1

while read -r line; do
    ids[${line%%:*}]=${line#*:}
done < SWIFT_CFG_DWWWDIR/.passwd

while read -r line; do
    group=${line%%:*}
    rest=${line#*:}
    for id in $rest; do
        groups[$id]+=",$group"
    done
done < SWIFT_CFG_DWWWDIR/.group

rm -f SWIFT_CFG_DWWWDIR/dbm.tmp
for id in "${!ids[@]}"; do
    dbmmanage SWIFT_CFG_DWWWDIR/dbm.tmp add "$id" "${ids[$id]}" ${groups[$id]#,}
done
dbmmanage SWIFT_CFG_DWWWDIR/dbm.tmp view > /dev/null 2>&1
if [[ $? != 0 ]] then
    print -u2 ERROR bad dbm file SWIFT_CFG_DWWWDIR/dbm.tmp - not using
    exit
fi
mv SWIFT_CFG_DWWWDIR/dbm.tmp SWIFT_CFG_DWWWDIR/.dbm
