
function add2path {
    export PATH=$1/bin:$PATH
    export FPATH=$1/fun:$FPATH
    export SWIFT_CFG_LDLIBRARYPATH=$1/lib:$SWIFT_CFG_LDLIBRARYPATH
}

export TZ=EST5EDT
add2path SWIFT_CFG_SWDIR
add2path SWIFT_CFG_WWWDIR
export SHELL=SWIFT_CFG_SWDIR/bin/ksh
export SHELLVERSION=SWIFT_CFG_SHELLVERSION

export SWMWSWMACCESS=SWIFT_CFG_WSWMACCESS
export SWMWSWMIDLE=SWIFT_CFG_WSWMIDLE

export SWMWATTEACCESS=SWIFT_CFG_WATTEACCESS

export SWMWCLOUDACCESS=SWIFT_CFG_WCLOUDACCESS
export SWMWCLOUDURL=SWIFT_CFG_WCLOUDURL
export SWMWCLOUDUSER=SWIFT_CFG_WCLOUDUSER

export SWMWEBIGACCESS=SWIFT_CFG_WEBIGACCESS
export SWMWEBIGURL=SWIFT_CFG_WEBIGURL

export SWMWBDACCESS=SWIFT_CFG_WBDACCESS

export TMPDIR=$SWMROOT/tmp

umask 002
