:PACKAGE: swift ast

CCFLAGS += $$(CC.DLL)

DDS_CC == "$(CC.CC:B:S)"
DDS_LD == "$(CC.SHARED.LD|LD:B:S)"
DDS_CCFLAGS == "$(CC.DLL)"
DDS_LDFLAGS == "$(CC.SHARED)"
DDS_ARCHCCFLAGS ==
DDS_ARCHLDFLAGS ==
DDS_APREFIX == "$(CC.PREFIX.SHARED)"
DDS_ASUFFIX == "$(CC.SUFFIX.SHARED)"
if CC.HOSTTYPE == "sgi.mips3*"
	DDS_LDFLAGS == "$(CC.SHARED:C!$(CC.SHARED.REGISTRY.PATH)!DDS_REGFILE!)"
	DDS_ARCHCCFLAGS == "-n32 -woff 1155,3421"
	DDS_ARCHLDFLAGS == "-n32 -woff 84,85"
end
if CC.HOSTTYPE == "sgi.mips4*"
	DDS_LDFLAGS == "$(CC.SHARED:C!$(CC.SHARED.REGISTRY.PATH)!DDS_REGFILE!)"
	DDS_ARCHCCFLAGS == "-64 -woff 1155,3421"
	DDS_ARCHLDFLAGS == "-64 -woff 84,85"
end
if CC.HOSTTYPE == "win32.*"
	DDS_RENAMEFROMDLL == 1
end

ddsmkso :: ddsmkso.sh
